### ISSUE TITLE
Crashes with forestry

### ISSUE THREAD

**Issue by FireFox1324** [aurilisdev/Electrodynamics#220]
When I have forestry installed it crashes on start. It goes straight to saving world instead of the main menu for some reason then crashes. Error: java.lang.NullPointerException: Rendering overlay, that's the error message I'm getting.

**Comment by FireFox1324** [comment]
it also crashes with iron furnaces. Error: java.lang.ArrayIndexOutOfBoundsException: 0, is the error message I get

**Comment by aurilisdev** [comment]
1.16 is no longer supported :/
